version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: elysia_postgres
    restart: always
    environment:
      POSTGRES_USER: ravi
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: elysiadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
